## 1. 라이브러리

In [31]:

import olefile
import glob
import pandas as pd
import os
from datetime import datetime as dt
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel
import numpy as np


## 2. input 파트

In [2]:

# '*'는 임의 길이의 모든 문자열을 의미
flist = glob.glob('hwpdata/*.hwp')
# 검사 문서
target = 'target.hwp'
# score 척도를 정할 변수를 base로 설정
base = 0
# empty dataframe 생성
df = pd.DataFrame()
# 파일 리스트에서 파일이름만 추출하여 리스트로 생성
names = [os.path.basename(x) for x in flist]


In [3]:
print(flist)

['hwpdata\\1. 민원상담위원 모집공고.hwp', 'hwpdata\\1.전문임기제공무원(속기사, 마급) 경력경쟁채용시험 공고문(배포용).hwp', 'hwpdata\\qweq.hwp', 'hwpdata\\target.hwp']


In [4]:
print(names)

['1. 민원상담위원 모집공고.hwp', '1.전문임기제공무원(속기사, 마급) 경력경쟁채용시험 공고문(배포용).hwp', 'qweq.hwp', 'target.hwp']


In [5]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [6]:
# 파일명을 title로 갖는 column생성
df['title'] = names
# 검사 문서의 df상 인덱스값을 index 변수에 저장
index = df[df['title'] == target].index[0]
# 빈 content 열 생성
content = []
# 코사인 유사도 항목 생성
df['cos_sim'] = np.nan
# 자카드 유사도 항목 생성
df['jac_sim'] = np.nan

In [7]:
print(df)

                                       title  cos_sim  jac_sim
0                         1. 민원상담위원 모집공고.hwp      NaN      NaN
1  1.전문임기제공무원(속기사, 마급) 경력경쟁채용시험 공고문(배포용).hwp      NaN      NaN
2                                   qweq.hwp      NaN      NaN
3                                 target.hwp      NaN      NaN


In [8]:
print(index)

3


In [9]:

for file in flist :
    # .hwp 파일을 읽기위해 olefile 임포트
    f = olefile.OleFileIO(file)
    # 읽어온 .hwp파일을 읽기 전용 파일 개체(BytesIO)로 encoded_text에 저장
    encoded_text = f.openstream('PrvText').read()
    # 읽기 전용 파일 개체를 'utf-16'방식으로 decoding
    decoded_text = encoded_text.decode('UTF-16')
    # decoding한 값을 content에 list 항목으로 저장
    content.append(decoded_text)

In [10]:
# print(encoded_text)
# print(decoded_text)
print(content, sep='\n')
len(content)

['서울중앙지방법원 공고 제 40호\r\n\r\n서울중앙지방법원 민원상담위원 모집 공고\r\n\r\n서울중앙지방법원은 청사를 방문하는 장애인, 외국인, 이주민 등 사회적 약자들을 위한 사법지원서비스를 집중적으로 제공하고, 민원인들에게 양질의 민원상담서비스를 제공하기 위하여 다음과 같이 민원상담위원을 모집합니다.\r\n\r\n2022. 11. 1.\r\n\r\n서울중앙지방법원장\r\n                                              \r\n\r\n1. 신청자격 및 모집인원\r\n\r\n\uf06d 신청자격\r\n   - 법무사 자격 보유자로서 개업하지 아니한 자\r\n   - 민원상담위원으로서의 업무수행능력을 구비한 자\r\n   - 민원상담위원으로서의 적합한 인품과 소양을 겸비한 자\r\n   - 아래 결격사유에 해당하지 아니한 자\r\n      · 피성년후견인 및 피한정후견인\r\n      · 금고 이상의 형을 받은 자\r\n      · 공무원으로서 면직의 징계처분을 받고, 당해 처분일로부터 2년을 경과하지 아니한 자\r\n      · 법무사로서 업무정지의 징계처분을 받고, 당해 처분일로부터 3년을 경과하지 아니한 자 \r\n      · 법원의 판결에 의하여 자격이 상실되거나 정지된 자\r\n\r\n\uf06d 모집인원 : 5명\r\n\r\n2. 활동 조건 \r\n\r\n\uf06d 위촉기간\r\n - 2023. 01. 01. ~  2023. 12. 31.\r\n\uf06d 신분 및 처우 \r\n   - 법원의 위촉을 받아 민원상담업무를 수행하는 자원봉사자 신분\r\n   - 매년 배정된 예산 등의 범위 내에서 소정의 상담수당을 지급\r\n\uf06d 활동방법\r\n   - 매일 오전 10:00 ~ 오후 5:00까지 6시간 근무 (점심시간 제외)\r\n   - 2인 1조, 격일·순환 근무 → 1인 주당 2.5회 근무\r\n     (근무 시간 및 형태는 협의하여 변경 가능)\r\n\r\n3. 지원서 접수 및 결과 발표

4

In [11]:
df['content'] = content

In [12]:
df

title  cos_sim  jac_sim  \
0                         1. 민원상담위원 모집공고.hwp      NaN      NaN   
1  1.전문임기제공무원(속기사, 마급) 경력경쟁채용시험 공고문(배포용).hwp      NaN      NaN   
2                                   qweq.hwp      NaN      NaN   
3                                 target.hwp      NaN      NaN   

                                             content  
0  서울중앙지방법원 공고 제 40호\r\n\r\n서울중앙지방법원 민원상담위원 모집 공고...  
1  서울중앙지방법원 공고 제2022 – 38호\r\n\r\n<전문임기제공무원(속기사, ...  
2  \r\n故 윤관 제12대 대법원장 법원장(法院葬] 절차 안내   \r\n\r\n20...  
3  서울중앙지방법원 공고 제2022 - 45호\r\n\r\n<전문임기제공무원(속기사, ...

In [13]:
df['content'][0]

'서울중앙지방법원 공고 제 40호\r\n\r\n서울중앙지방법원 민원상담위원 모집 공고\r\n\r\n서울중앙지방법원은 청사를 방문하는 장애인, 외국인, 이주민 등 사회적 약자들을 위한 사법지원서비스를 집중적으로 제공하고, 민원인들에게 양질의 민원상담서비스를 제공하기 위하여 다음과 같이 민원상담위원을 모집합니다.\r\n\r\n2022. 11. 1.\r\n\r\n서울중앙지방법원장\r\n                                              \r\n\r\n1. 신청자격 및 모집인원\r\n\r\n\uf06d 신청자격\r\n   - 법무사 자격 보유자로서 개업하지 아니한 자\r\n   - 민원상담위원으로서의 업무수행능력을 구비한 자\r\n   - 민원상담위원으로서의 적합한 인품과 소양을 겸비한 자\r\n   - 아래 결격사유에 해당하지 아니한 자\r\n      · 피성년후견인 및 피한정후견인\r\n      · 금고 이상의 형을 받은 자\r\n      · 공무원으로서 면직의 징계처분을 받고, 당해 처분일로부터 2년을 경과하지 아니한 자\r\n      · 법무사로서 업무정지의 징계처분을 받고, 당해 처분일로부터 3년을 경과하지 아니한 자 \r\n      · 법원의 판결에 의하여 자격이 상실되거나 정지된 자\r\n\r\n\uf06d 모집인원 : 5명\r\n\r\n2. 활동 조건 \r\n\r\n\uf06d 위촉기간\r\n - 2023. 01. 01. ~  2023. 12. 31.\r\n\uf06d 신분 및 처우 \r\n   - 법원의 위촉을 받아 민원상담업무를 수행하는 자원봉사자 신분\r\n   - 매년 배정된 예산 등의 범위 내에서 소정의 상담수당을 지급\r\n\uf06d 활동방법\r\n   - 매일 오전 10:00 ~ 오후 5:00까지 6시간 근무 (점심시간 제외)\r\n   - 2인 1조, 격일·순환 근무 → 1인 주당 2.5회 근무\r\n     (근무 시간 및 형태는 협의하여 변경 가능)\r\n\r\n3. 지원서 접수 및 결과 발표\

## 3. 벡터화 및 유사도 측정

In [14]:
# 자연어를 벡터화하기 위한 Tf-idf 적용
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['content'])


In [15]:
type(tfidf_matrix)

scipy.sparse.csr.csr_matrix

In [16]:
# 문서의 각단어별로 문서에 대한 정보를 얼마나 갖고 있느냐를 뜻하는 값
print(tfidf_matrix) #  (a,b)는 array로 만들었을 때 각 뒤에 나오는 tf-idf 값의 위치
print(tfidf_matrix.shape)
print(tfidf.get_feature_names_out())
print(len(tfidf.get_feature_names_out()))

  (0, 376)	0.06867105927561698
  (0, 170)	0.06867105927561698
  (0, 83)	0.06867105927561698
  (0, 384)	0.06867105927561698
  (0, 16)	0.05414105189732176
  (0, 3)	0.06867105927561698
  (0, 7)	0.06867105927561698
  (0, 93)	0.06867105927561698
  (0, 168)	0.06867105927561698
  (0, 66)	0.06867105927561698
  (0, 318)	0.2060131778268509
  (0, 354)	0.06867105927561698
  (0, 53)	0.06867105927561698
  (0, 181)	0.06867105927561698
  (0, 406)	0.06867105927561698
  (0, 408)	0.06867105927561698
  (0, 221)	0.06867105927561698
  (0, 46)	0.06867105927561698
  (0, 348)	0.06867105927561698
  (0, 18)	0.05414105189732176
  (0, 220)	0.06867105927561698
  (0, 63)	0.06867105927561698
  (0, 19)	0.06867105927561698
  (0, 29)	0.06867105927561698
  (0, 336)	0.13734211855123396
  :	:
  (3, 338)	0.19068915535857267
  (3, 397)	0.06356305178619089
  (3, 223)	0.06356305178619089
  (3, 26)	0.06356305178619089
  (3, 144)	0.19068915535857267
  (3, 380)	0.25425220714476354
  (3, 39)	0.06356305178619089
  (3, 297)	0.050113

#### 3-1. 코사인 유사도

In [17]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [18]:
print(cosine_sim)

[[1.         0.05830587 0.05806165 0.05193522]
 [0.05830587 1.         0.01336071 0.12851837]
 [0.05806165 0.01336071 1.         0.03405808]
 [0.05193522 0.12851837 0.03405808 1.        ]]


In [19]:
sim_scores = list(enumerate(cosine_sim[index]))


In [20]:
print(sim_scores)

[(0, 0.05193521834770416), (1, 0.12851837004036096), (2, 0.03405808418379918), (3, 1.0)]


In [21]:
sim_scores = sorted(sim_scores, key=lambda x:x[1], reverse=True)
for key, score in sim_scores :
    if score > base :
        print(df.iloc[key]['title'], score)

target.hwp 1.0
1.전문임기제공무원(속기사, 마급) 경력경쟁채용시험 공고문(배포용).hwp 0.12851837004036096
1. 민원상담위원 모집공고.hwp 0.05193521834770416
qweq.hwp 0.03405808418379918


-----------------------

#### 3-2. 자카드 유사도

In [22]:
df['content']

0    서울중앙지방법원 공고 제 40호\r\n\r\n서울중앙지방법원 민원상담위원 모집 공고...
1    서울중앙지방법원 공고 제2022 – 38호\r\n\r\n<전문임기제공무원(속기사, ...
2    \r\n故 윤관 제12대 대법원장 법원장(法院葬] 절차 안내   \r\n\r\n20...
3    서울중앙지방법원 공고 제2022 - 45호\r\n\r\n<전문임기제공무원(속기사, ...
Name: content, dtype: object

In [23]:
import konlpy
konlpy.__version__

'0.6.0'

In [24]:
from konlpy.tag import *

okt = Okt()


In [25]:
target = okt.morphs(df['content'][index])


In [26]:
for num_content in range(len(df)):
    compare = okt.morphs(df['content'][num_content])
    union = set(target).union(set(compare))
    # print('문서1과 문서2의 합집합 :',union)
    intersection = set(target).intersection(set(compare))
    # print('문서1과 문서2의 교집합 :',intersection)
    # print(f'{num_content}번 text와의 자카드 유사도 :',len(intersection)/len(union))
    score = len(intersection)/len(union)
    print(df.iloc[num_content]['title'], len(intersection)/len(union))


1. 민원상담위원 모집공고.hwp 0.15845070422535212
1.전문임기제공무원(속기사, 마급) 경력경쟁채용시험 공고문(배포용).hwp 0.27380952380952384
qweq.hwp 0.07120743034055728
target.hwp 1.0


In [27]:
df

title  cos_sim  jac_sim  \
0                         1. 민원상담위원 모집공고.hwp      NaN      NaN   
1  1.전문임기제공무원(속기사, 마급) 경력경쟁채용시험 공고문(배포용).hwp      NaN      NaN   
2                                   qweq.hwp      NaN      NaN   
3                                 target.hwp      NaN      NaN   

                                             content  
0  서울중앙지방법원 공고 제 40호\r\n\r\n서울중앙지방법원 민원상담위원 모집 공고...  
1  서울중앙지방법원 공고 제2022 – 38호\r\n\r\n<전문임기제공무원(속기사, ...  
2  \r\n故 윤관 제12대 대법원장 법원장(法院葬] 절차 안내   \r\n\r\n20...  
3  서울중앙지방법원 공고 제2022 - 45호\r\n\r\n<전문임기제공무원(속기사, ...

------------

#### 3-3. 유클리드 거리

In [28]:
from konlpy.tag import *

okt = Okt()

In [29]:
target = okt.morphs(df['content'][index])

In [42]:
compare = okt.morphs(df['content'][0])

In [53]:
len(target)

382

In [ ]:
target

In [74]:
compare

['서울',
 '중앙',
 '지방법원',
 '공고',
 '제',
 '40',
 '호',
 '\r\n\r\n',
 '서울',
 '중앙',
 '지방법원',
 '민원',
 '상담',
 '위원',
 '모집',
 '공고',
 '\r\n\r\n',
 '서',
 '울',
 '중앙',
 '지방법원',
 '은',
 '청사',
 '를',
 '방문',
 '하는',
 '장애인',
 ',',
 '외국인',
 ',',
 '이',
 '주민',
 '등',
 '사회',
 '적',
 '약자',
 '들',
 '을',
 '위',
 '한',
 '사법',
 '지',
 '원',
 '서비스',
 '를',
 '집중',
 '적',
 '으로',
 '제공',
 '하고',
 ',',
 '민원',
 '인들',
 '에게',
 '양질',
 '의',
 '민원',
 '상담',
 '서비스',
 '를',
 '제공',
 '하기',
 '위',
 '하여',
 '다음',
 '과',
 '같이',
 '민원',
 '상담',
 '위원',
 '을',
 '모집',
 '합니다',
 '.',
 '\r\n\r\n',
 '2022',
 '.',
 '11',
 '.',
 '1',
 '.',
 '\r\n\r\n',
 '서',
 '울',
 '중앙',
 '지방법원',
 '장',
 '\r\n                                              \r\n\r\n',
 '1',
 '.',
 '신청',
 '자격',
 '및',
 '모집',
 '인원',
 '\r\n\r\n',
 '\uf06d',
 '신청',
 '자격',
 '\r\n   ',
 '-',
 '법무사',
 '자격',
 '보유',
 '자',
 '로서',
 '개업',
 '하지',
 '아니한',
 '자',
 '\r\n   ',
 '-',
 '민원',
 '상담',
 '위원',
 '으로서의',
 '업무',
 '수행',
 '능력',
 '을',
 '구비',
 '한',
 '자',
 '\r\n   ',
 '-',
 '민원',
 '상담',
 '위원',
 '으로서의',
 '적합한',
 '인품',


In [33]:
df['content'][0]

'서울중앙지방법원 공고 제 40호\r\n\r\n서울중앙지방법원 민원상담위원 모집 공고\r\n\r\n서울중앙지방법원은 청사를 방문하는 장애인, 외국인, 이주민 등 사회적 약자들을 위한 사법지원서비스를 집중적으로 제공하고, 민원인들에게 양질의 민원상담서비스를 제공하기 위하여 다음과 같이 민원상담위원을 모집합니다.\r\n\r\n2022. 11. 1.\r\n\r\n서울중앙지방법원장\r\n                                              \r\n\r\n1. 신청자격 및 모집인원\r\n\r\n\uf06d 신청자격\r\n   - 법무사 자격 보유자로서 개업하지 아니한 자\r\n   - 민원상담위원으로서의 업무수행능력을 구비한 자\r\n   - 민원상담위원으로서의 적합한 인품과 소양을 겸비한 자\r\n   - 아래 결격사유에 해당하지 아니한 자\r\n      · 피성년후견인 및 피한정후견인\r\n      · 금고 이상의 형을 받은 자\r\n      · 공무원으로서 면직의 징계처분을 받고, 당해 처분일로부터 2년을 경과하지 아니한 자\r\n      · 법무사로서 업무정지의 징계처분을 받고, 당해 처분일로부터 3년을 경과하지 아니한 자 \r\n      · 법원의 판결에 의하여 자격이 상실되거나 정지된 자\r\n\r\n\uf06d 모집인원 : 5명\r\n\r\n2. 활동 조건 \r\n\r\n\uf06d 위촉기간\r\n - 2023. 01. 01. ~  2023. 12. 31.\r\n\uf06d 신분 및 처우 \r\n   - 법원의 위촉을 받아 민원상담업무를 수행하는 자원봉사자 신분\r\n   - 매년 배정된 예산 등의 범위 내에서 소정의 상담수당을 지급\r\n\uf06d 활동방법\r\n   - 매일 오전 10:00 ~ 오후 5:00까지 6시간 근무 (점심시간 제외)\r\n   - 2인 1조, 격일·순환 근무 → 1인 주당 2.5회 근무\r\n     (근무 시간 및 형태는 협의하여 변경 가능)\r\n\r\n3. 지원서 접수 및 결과 발표\

In [44]:
vect = CountVectorizer()
dtm_T = vect.fit_transform(target).toarray()
dtm_C = vect.fit_transform(compare).toarray()


In [46]:
print(dtm_T, dtm_C, sep="\n")
print(dtm_T.shape, dtm_C.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(382, 86) (377, 129)


In [85]:
np.pad(dtm_C, pad_width=((1,1),(3,1)), mode='constant', constant_values=0)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [91]:
print(tfidf_matrix[0])

  (0, 376)	0.06867105927561698
  (0, 170)	0.06867105927561698
  (0, 83)	0.06867105927561698
  (0, 384)	0.06867105927561698
  (0, 16)	0.05414105189732176
  (0, 3)	0.06867105927561698
  (0, 7)	0.06867105927561698
  (0, 93)	0.06867105927561698
  (0, 168)	0.06867105927561698
  (0, 66)	0.06867105927561698
  (0, 318)	0.2060131778268509
  (0, 354)	0.06867105927561698
  (0, 53)	0.06867105927561698
  (0, 181)	0.06867105927561698
  (0, 406)	0.06867105927561698
  (0, 408)	0.06867105927561698
  (0, 221)	0.06867105927561698
  (0, 46)	0.06867105927561698
  (0, 348)	0.06867105927561698
  (0, 18)	0.05414105189732176
  (0, 220)	0.06867105927561698
  (0, 63)	0.06867105927561698
  (0, 19)	0.06867105927561698
  (0, 29)	0.06867105927561698
  (0, 336)	0.13734211855123396
  :	:
  (0, 155)	0.06867105927561698
  (0, 57)	0.04383184759900136
  (0, 121)	0.04383184759900136
  (0, 263)	0.06867105927561698
  (0, 335)	0.06867105927561698
  (0, 151)	0.06867105927561698
  (0, 240)	0.06867105927561698
  (0, 156)	0.06867

In [95]:
def l1_normalize(v):
    norm = np.sum(v)
    return v / norm

In [96]:
tfidf_norm_l1 = l1_normalize(tfidf_matrix)

In [98]:
print(tfidf_norm_l1)

  (0, 376)	0.0018509295554199607
  (0, 170)	0.0018509295554199607
  (0, 83)	0.0018509295554199607
  (0, 384)	0.0018509295554199607
  (0, 16)	0.0014592941215028088
  (0, 3)	0.0018509295554199607
  (0, 7)	0.0018509295554199607
  (0, 93)	0.0018509295554199607
  (0, 168)	0.0018509295554199607
  (0, 66)	0.0018509295554199607
  (0, 318)	0.005552788666259882
  (0, 354)	0.0018509295554199607
  (0, 53)	0.0018509295554199607
  (0, 181)	0.0018509295554199607
  (0, 406)	0.0018509295554199607
  (0, 408)	0.0018509295554199607
  (0, 221)	0.0018509295554199607
  (0, 46)	0.0018509295554199607
  (0, 348)	0.0018509295554199607
  (0, 18)	0.0014592941215028088
  (0, 220)	0.0018509295554199607
  (0, 63)	0.0018509295554199607
  (0, 19)	0.0018509295554199607
  (0, 29)	0.0018509295554199607
  (0, 336)	0.0037018591108399215
  :	:
  (3, 338)	0.00513975169852336
  (3, 397)	0.0017132505661744534
  (3, 223)	0.0017132505661744534
  (3, 26)	0.0017132505661744534
  (3, 144)	0.00513975169852336
  (3, 380)	0.00685300226

In [105]:
num_content

3

In [107]:
print(df.iloc[0]['title'], euclidean_distances(tfidf_norm_l1[3], tfidf_norm_l1[0]))
print(df.iloc[1]['title'], euclidean_distances(tfidf_norm_l1[3], tfidf_norm_l1[1]))
print(df.iloc[2]['title'], euclidean_distances(tfidf_norm_l1[3], tfidf_norm_l1[2]))

1. 민원상담위원 모집공고.hwp [[0.03711506]]
1.전문임기제공무원(속기사, 마급) 경력경쟁채용시험 공고문(배포용).hwp [[0.03558445]]
qweq.hwp [[0.03746335]]


In [94]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[1], tfidf_matrix[3])

array([[1.32021334]])

In [86]:
dtm_C.shape

(377, 129)

In [41]:
def dist(x, y):
    return np.sqrt(np.sum((x-y)**2))

In [47]:
dist(dtm_T, dtm_C)

ValueError: operands could not be broadcast together with shapes (382,86) (377,129) 

In [58]:
print(tfidf_matrix[0])

  (0, 376)	0.06867105927561698
  (0, 170)	0.06867105927561698
  (0, 83)	0.06867105927561698
  (0, 384)	0.06867105927561698
  (0, 16)	0.05414105189732176
  (0, 3)	0.06867105927561698
  (0, 7)	0.06867105927561698
  (0, 93)	0.06867105927561698
  (0, 168)	0.06867105927561698
  (0, 66)	0.06867105927561698
  (0, 318)	0.2060131778268509
  (0, 354)	0.06867105927561698
  (0, 53)	0.06867105927561698
  (0, 181)	0.06867105927561698
  (0, 406)	0.06867105927561698
  (0, 408)	0.06867105927561698
  (0, 221)	0.06867105927561698
  (0, 46)	0.06867105927561698
  (0, 348)	0.06867105927561698
  (0, 18)	0.05414105189732176
  (0, 220)	0.06867105927561698
  (0, 63)	0.06867105927561698
  (0, 19)	0.06867105927561698
  (0, 29)	0.06867105927561698
  (0, 336)	0.13734211855123396
  :	:
  (0, 155)	0.06867105927561698
  (0, 57)	0.04383184759900136
  (0, 121)	0.04383184759900136
  (0, 263)	0.06867105927561698
  (0, 335)	0.06867105927561698
  (0, 151)	0.06867105927561698
  (0, 240)	0.06867105927561698
  (0, 156)	0.06867

In [67]:
print(tfidf_matrix[3])

  (0, 193)	0.06356305178619089
  (0, 82)	0.06356305178619089
  (0, 396)	0.06356305178619089
  (0, 398)	0.06356305178619089
  (0, 71)	0.06356305178619089
  (0, 414)	0.06356305178619089
  (0, 311)	0.06356305178619089
  (0, 346)	0.06356305178619089
  (0, 393)	0.06356305178619089
  (0, 129)	0.06356305178619089
  (0, 379)	0.06356305178619089
  (0, 134)	0.06356305178619089
  (0, 183)	0.06356305178619089
  (0, 350)	0.06356305178619089
  (0, 133)	0.06356305178619089
  (0, 204)	0.06356305178619089
  (0, 413)	0.06356305178619089
  (0, 54)	0.06356305178619089
  (0, 302)	0.06356305178619089
  (0, 301)	0.06356305178619089
  (0, 164)	0.06356305178619089
  (0, 276)	0.06356305178619089
  (0, 30)	0.572067466075718
  (0, 62)	0.06356305178619089
  (0, 402)	0.06356305178619089
  :	:
  (0, 338)	0.19068915535857267
  (0, 397)	0.06356305178619089
  (0, 223)	0.06356305178619089
  (0, 26)	0.06356305178619089
  (0, 144)	0.19068915535857267
  (0, 380)	0.25425220714476354
  (0, 39)	0.06356305178619089
  (0, 297)	

In [ ]:
tfidf_matrix[3]

In [35]:
vocab = vect.get_feature_names_out()
pd.DataFrame(dtm, columns=vocab)

10  11  12  15  18  20  2022  21  24  25  ...  최종  출력  학교  학력  합격자  합니다  \
0     0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
1     0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
2     0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
3     0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
4     0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
..   ..  ..  ..  ..  ..  ..   ...  ..  ..  ..  ...  ..  ..  ..  ..  ...  ...   
377   0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
378   0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
379   0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
380   0   0   0   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   
381   0   0   1   0   0   0     0   0   0   0  ...   0   0   0   0    0    0   

     해당  행정  후견  휴학  
0     0   0   0   0  
1     0   0   0   0  
2     0   0   0   0  
3     0   0   0   0  
4     0   0   0   0  
..   ..  ..  ..  ..  
377   0   0   0   0  
378   0   0   0   0  
379   0   0   0   0  
380   0   0   0   0  
381   0   0   0   0  

[382 rows x 86 columns]

In [36]:
tfidfv = TfidfVectorizer(vocabulary=vocab)
tfidf = tfidfv.fit_transform(target).toarray()
pd.DataFrame(tfidf, columns=vocab)

10   11   12   15   18   20  2022   21   24   25  ...   최종   출력   학교  \
0    0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...   ...  ...  ...  ...  ...  ...  ...  ...   
377  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
378  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
379  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
380  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
381  0.0  0.0  1.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      학력  합격자  합니다   해당   행정   후견   휴학  
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
377  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
378  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
379  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
380  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
381  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[382 rows x 86 columns]